### ISSUE TITLE
Transpose Matrix tool

### ISSUE THREAD

**Issue by matthewjohnrossi** [CEGRcode/scriptmanager#14]
Can the "Output for Composite" be altered  so that...

1.) the output is transposed (I would like the bed file coordinates output in column instead of a row).

2.) the antisense values get output as negative values.

**Comment by owlang** [comment]
Instead, write a new tool that will transpose tab delimited files that would allow a user to transpose the composite (or a CDT with row start-stop options). The second point about negative values will be left to the user to handle in Locus Plotter or Excel.
