### ISSUE TITLE
Scriptmanager does not accept output of MultiGPS

### ISSUE THREAD

**Issue by matthewjohnrossi** [CEGRcode/scriptmanager#25]
Scriptmanager does not function with the five column experiment.bed output of multiGPS (the peak file). It also doesn't accpet the "track" info in the first row. I currently have to remake all the bed files by removing the first line and adding a sixth column. Can we make scriptmanager and multiGPS compatible?

**Comment by WilliamKMLai** [comment]
Can you give me a sample file and which script this is failing on? Scriptmanager should be parsing out the track line and non-strand cases already
