### ISSUE TITLE
New HeatMap tool for positive/negative values

### ISSUE THREAD

**Issue by owlang** [CEGRcode/scriptmanager#48]
Create a new heatmap tool that will use one color for positive values and a different color for negative values (and I guess technically a third color, white, for the zero values).

**Comment by WilliamKMLai** [comment]
The heatmap tool we use is originally based on:
http://jtreeview.sourceforge.net/

The idea for a truly flexible heatmap tool is to use 4 colors. Color 1: High values, Color 2: Medium values, Color 3: Low values, Color 4: NaN values (typically grey)
Much like the 2-color heatmap tool currently in use, the upgraded one should be able to set thresholds for what constitutes high/medium/low either automatically (Lowest 5%, Median, Highest 95%) or take in user-defined numbers.
