### ISSUE TITLE
Trace Images - using transparent colors in Heatmap

### ISSUE THREAD

**Issue by owlang** [CEGRcode/scriptmanager#66]
Sometimes we wish to create traces of gene annotations over the heatmaps we generate. By adjusting the alpha-channel color selection (the tool currently allows user selection but the script does not use the alpha channel value), we can create trace images from CDT files to overlay onto heatmap PNGs.
-retrieve and use alpha-channel values from color selection tool
-use transparent colors for image initialization in script
-allow for and interpret encoding of alpha values in CLI color selection HEX value

**Comment by owlang** [comment]
Question: do we want to add user selection of alpha channels for Two Color Heatmap?

**Comment by WilliamKMLai** [comment]
Yes, especially since we presumably already have the code to do this under the 3-color heatmap function.
